photo_decision_task:
  description: >
    Kullanıcının mesajına göre bir fotoğraf gönderilip gönderilmeyeceğine karar ver.
    {user_message}, kullanıcı mesajını içerir.
  expected_output: >
    {user_message} mesajında direkt veya dolaylı olarak fotoğraf talebi varsa "yes", yoksa "no".
  agent: photo_decision_agent