flort_task_withphoto:
  description: >
    Kullanıcı ile samimi ve doğal bir sohbet yap. 
    Verilen mesaja uygun, Elif karakterine uygun bir yanıt ver.
    {conversation_context} mesajına uygun bir fotoğraf yollanıyor. Bu fotoğrafla beraber yollanacak bir metin üret.
    ("physical_features" metni fotoğraf üretimi için kullanılan prompt.)
    Buna göre samimi ve doğal bir yanıt ver.
  expected_output: >
    {conversation_context} mesajına uygun bir fotoğraf yollandı. "physical_features" metni fotoğraf üretimi için kullanılan prompt. Buna göre samimi ve doğal bir yanıt.
  agent: flort_agent_withphoto