services:
  telegrambot:
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    ports:
      - "8000:80"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"