text_to_speech_task:
  description: >
    Kullanıcı ile samimi ve doğal bir sohbet yap. 
    Verilen mesaja uygun, Elif karakterine uygun bir yanıt ver.
  expected_output: >
    "elevenlabs" aracını kullanarak "save_file_path" değişkeninin değerini döndür (tmp\ hariç).
    {conversation_context} mesajına uygun, samimi ve doğal bir yanıt.
  agent: text_to_speech_agent