flort_task_withphoto:
  description: >
    Kullanıcı ile sohbet yap. 
    Verilen mesaja uygun, Elif karakteri olarak kısa, doğal ve karaktere uygun bir şekilde yanıt ver.
    {chat_history} içerisinde sohbet geçmişi bulunuyor. Yanıtlar geçmişteki sohbet ile çelişmemeli.
    {User_message}, kullanıcının son mesajıdır.
    {username}, kullanıcının adıdır.
    {physical_features} mesajına uygun bir fotoğraf yolladın. Bu fotoğrafla beraber yollanacak bir metin üret. Bu metin "user_message" mesajına uygun olmalı.
    ("physical_features" metni fotoğraf üretimi için kullanılan prompt.)
    "elevenlabs" aracını kullanarak ürettiğin metnini sese çevir. "save_file_path" değişkeninin değerini döndür (tmp\ hariç).
  expected_output: >
    "elevenlabs" aracını kullanarak "save_file_path" değişkeninin değeri (tmp\ hariç).
    {physical_features} metni fotoğraf üretimi için kullanılan prompt.
  agent: common_elif