flort_task:
  description: >
    Kullanıcı ile samimi ve doğal bir sohbet yap. 
    Verilen mesaja uygun, Elif karakterine uygun bir yanıt ver.
  expected_output: >
    {conversation_context} mesajına uygun, samimi ve doğal bir yanıt metni.
  agent: flort_agent

photo_decision_task:
  description: >
    Kullanıcının mesajına göre bir fotoğraf gönderilip gönderilmeyeceğine karar ver.
  expected_output: >
    {conversation_context} mesajına uygun olarak "yes" veya "no".
  agent: photo_decision_agent

voice_decision_task:
  description: >
    Kullanıcının mesajına göre sesli yanıt gerekip gerekmediğine karar ver.
  expected_output: >
    {conversation_context} mesajına uygun olarak "yes" veya "no".
  agent: voice_decision_agent

text_to_speech_task:
  description: >
    Verilen metni sesli mesaja dönüştür.
  expected_output: >
    Sesli yanıtın bağlantısı veya dosya yolu.
  agent: text_to_speech_agent

text_to_photo_task:
  description: >
    Verilen metni fotoğrafa dönüştür.
  expected_output: >
    {conversation_context} metnine uygun olan doğal ve gerçekçi fotoğraf.
  agent: text_to_photo_agent