text_to_photo_task:
  description: >
    Verilen metni fotoğrafa dönüştür.
  expected_output: >
    {conversation_context} metnindeki physical_features değişkenine uygun olan doğal ve gerçekçi fotoğraf, dalle aracını kullan.
    Çıktı olarak sadece image_data değişkenindeki değeri döndür.
  agent: text_to_photo_agent